<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RpgWorld.Application\RpgWorld.Application.csproj" />
    <ProjectReference Include="..\..\src\RpgWorld.Domain\RpgWorld.Domain.csproj" />
    <ProjectReference Include="..\..\src\RpgWorld.Simulation\RpgWorld.Simulation.csproj" />
  </ItemGroup>

</Project>
