// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RpgWorld.Infrastructure.Persistence;

#nullable disable

namespace RpgWorld.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RpgWorldDbContext))]
    [Migration("20260830215640_ImportedWorldSource")]
    partial class ImportedWorldSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rpg_world")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("integer")
                        .HasColumnName("coordinate_x");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("integer")
                        .HasColumnName("coordinate_y");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("OriginX")
                        .HasColumnType("integer")
                        .HasColumnName("origin_x");

                    b.Property<int>("OriginY")
                        .HasColumnType("integer")
                        .HasColumnName("origin_y");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "CoordinateX", "CoordinateY")
                        .IsUnique()
                        .HasDatabaseName("ux_chunks_world_coordinate");

                    b.ToTable("chunks", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Tile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BiomeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("biome_code");

                    b.Property<short>("Elevation")
                        .HasColumnType("smallint")
                        .HasColumnName("elevation");

                    b.Property<decimal>("Humidity")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("humidity");

                    b.Property<Guid?>("ResourceDepositId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_deposit_id");

                    b.Property<Guid?>("StructureId")
                        .HasColumnType("uuid")
                        .HasColumnName("structure_id");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("temperature_celsius");

                    b.Property<string>("TerrainCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("terrain_code");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.PrimitiveCollection<Guid[]>("_occupantIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("occupant_ids");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("ux_tiles_world_position");

                    b.ToTable("tiles", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.World", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_size");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("worlds", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.PersistenceCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_persistence_checkpoints_created_at_utc");

                    b.ToTable("persistence_checkpoints", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.WorldMapSourceImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("GridResolution")
                        .HasColumnType("integer")
                        .HasColumnName("grid_resolution");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("media_type");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_height");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_width");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_world_source_image_sha256");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_world_source_image_world");

                    b.ToTable("world_map_source_images", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Chunk", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Tile", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.WorldMapSourceImage", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithOne()
                        .HasForeignKey("RpgWorld.Infrastructure.Persistence.WorldMapSourceImage", "WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
