// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RpgWorld.Infrastructure.Persistence;

#nullable disable

namespace RpgWorld.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RpgWorldDbContext))]
    [Migration("20260831201434_PlayerFogOfWar")]
    partial class PlayerFogOfWar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rpg_world")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RpgWorld.Domain.Actors.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentAction")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("current_action");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<int>("MaximumHealth")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_health");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.Property<string>("_attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("_inventory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory");

                    b.Property<string>("_relationships")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("relationships");

                    b.Property<string>("_reputation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reputation");

                    b.Property<string>("actor_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Status")
                        .HasDatabaseName("ix_actors_world_status");

                    b.HasIndex("WorldId", "X", "Y")
                        .HasDatabaseName("ix_actors_world_position");

                    b.ToTable("actors", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_actors_npc_energy", "actor_type <> 'npc' OR (energy IS NOT NULL AND energy BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_hunger", "actor_type <> 'npc' OR (hunger IS NOT NULL AND hunger BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_money", "actor_type <> 'npc' OR (money IS NOT NULL AND money >= 0)");

                            t.HasCheckConstraint("ck_actors_npc_state_required", "actor_type <> 'npc' OR (needs_updated_at IS NOT NULL AND family_ids IS NOT NULL AND goals IS NOT NULL)");

                            t.HasCheckConstraint("ck_actors_npc_traits_required", "actor_type <> 'npc' OR trait_codes IS NOT NULL");
                        });

                    b.HasDiscriminator<string>("actor_type").HasValue("Actor");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Housing.HousingConstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("ConsumedStone")
                        .HasColumnType("integer")
                        .HasColumnName("consumed_stone");

                    b.Property<int>("ConsumedWood")
                        .HasColumnType("integer")
                        .HasColumnName("consumed_wood");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_actor_id");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<int>("RequiredStone")
                        .HasColumnType("integer")
                        .HasColumnName("required_stone");

                    b.Property<int>("RequiredWood")
                        .HasColumnType("integer")
                        .HasColumnName("required_wood");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.Property<string>("_residentActorIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resident_actor_ids");

                    b.HasKey("Id");

                    b.HasIndex("OwnerActorId")
                        .IsUnique()
                        .HasDatabaseName("ux_housing_constructions_active_owner")
                        .HasFilter("status = 'InProgress'");

                    b.HasIndex("WorldId", "Status")
                        .HasDatabaseName("ix_housing_constructions_world_status");

                    b.HasIndex("WorldId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("ux_housing_constructions_world_position");

                    b.ToTable("housing_constructions", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_housing_constructions_progress", "progress BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Memories.NpcMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<string>("_payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_npc_memories_expiration")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("ActorId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_npc_memories_actor_created");

                    b.HasIndex("ActorId", "TargetId", "Importance")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_npc_memories_actor_target_importance");

                    b.ToTable("npc_memories", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_npc_memories_importance", "importance BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.PlayerTileKnowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at_utc");

                    b.Property<string>("HistoricalState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("historical_state");

                    b.Property<DateTimeOffset?>("KnownAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("known_at_utc");

                    b.Property<DateTimeOffset>("LastVisibleAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visible_at_utc");

                    b.Property<Guid>("PlayerActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_actor_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("PlayerActorId", "HistoricalState")
                        .HasDatabaseName("ix_player_tile_knowledge_player_state");

                    b.HasIndex("PlayerActorId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("ux_player_tile_knowledge_player_position");

                    b.ToTable("player_tile_knowledge", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_player_tile_knowledge_historical_state", "historical_state IN ('Discovered', 'Known')");

                            t.HasCheckConstraint("ck_player_tile_knowledge_position", "x >= 0 AND y >= 0");

                            t.HasCheckConstraint("ck_player_tile_knowledge_version", "version >= 0");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AggregateEconomicOutput")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("aggregate_economic_output");

                    b.Property<decimal>("AggregateMilitaryStrength")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("aggregate_military_strength");

                    b.Property<int>("AggregatePopulation")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_population");

                    b.Property<decimal>("AggregateProductionOutput")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("aggregate_production_output");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("integer")
                        .HasColumnName("coordinate_x");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("integer")
                        .HasColumnName("coordinate_y");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("OriginX")
                        .HasColumnType("integer")
                        .HasColumnName("origin_x");

                    b.Property<int>("OriginY")
                        .HasColumnType("integer")
                        .HasColumnName("origin_y");

                    b.Property<string>("SimulationLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Abstract")
                        .HasColumnName("simulation_level");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "CoordinateX", "CoordinateY")
                        .IsUnique()
                        .HasDatabaseName("ux_chunks_world_coordinate");

                    b.ToTable("chunks", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Cities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CenterX")
                        .HasColumnType("integer")
                        .HasColumnName("center_x");

                    b.Property<int>("CenterY")
                        .HasColumnType("integer")
                        .HasColumnName("center_y");

                    b.Property<DateTimeOffset?>("DestroyedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("destroyed_at_utc");

                    b.Property<long>("EconomicCycleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("economic_cycle_count");

                    b.Property<DateTimeOffset>("FoundedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("founded_at_utc");

                    b.Property<Guid?>("GoverningFactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("governing_faction_id");

                    b.Property<DateTimeOffset?>("LastEconomicCycleAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_economic_cycle_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<decimal>("Wealth")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("wealth");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<string>("_buildingIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("building_ids");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history");

                    b.Property<string>("_residentActorIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resident_actor_ids");

                    b.Property<string>("_resourceMarkets")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_markets")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("_resourceStocks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_stocks");

                    b.HasKey("Id");

                    b.HasIndex("GoverningFactionId")
                        .HasDatabaseName("ix_cities_governing_faction");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_cities_world_name");

                    b.HasIndex("WorldId", "Status")
                        .HasDatabaseName("ix_cities_world_status");

                    b.ToTable("cities", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_cities_destroyed_state", "(status = 'Destroyed' AND destroyed_at_utc IS NOT NULL AND population = 0) OR (status <> 'Destroyed' AND destroyed_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_cities_economic_cycle_count", "economic_cycle_count >= 0");

                            t.HasCheckConstraint("ck_cities_population", "population >= 0");

                            t.HasCheckConstraint("ck_cities_version", "version >= 0");

                            t.HasCheckConstraint("ck_cities_wealth", "wealth >= 0");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Cities.CityTerritoryTile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_city_territory_city");

                    b.HasIndex("WorldId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("ux_city_territory_world_active_position")
                        .HasFilter("is_active");

                    b.ToTable("city_territory_tiles", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_city_territory_tiles_active", "(is_active AND released_at_utc IS NULL) OR (NOT is_active AND released_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_city_territory_tiles_x", "x >= 0");

                            t.HasCheckConstraint("ck_city_territory_tiles_y", "y >= 0");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Events.WorldConsequence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<decimal>("Magnitude")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("magnitude");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "OccurredAtUtc")
                        .HasDatabaseName("ix_world_consequences_world_time");

                    b.HasIndex("SourceEventId", "Kind", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("ux_world_consequences_source_kind_target");

                    b.ToTable("world_consequences", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_world_consequences_magnitude", "magnitude >= -100 AND magnitude <= 100");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Events.WorldEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CausalityDepth")
                        .HasColumnType("integer")
                        .HasColumnName("causality_depth");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("integer")
                        .HasColumnName("payload_version");

                    b.Property<int?>("PositionX")
                        .HasColumnType("integer")
                        .HasColumnName("position_x");

                    b.Property<int?>("PositionY")
                        .HasColumnType("integer")
                        .HasColumnName("position_y");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("type");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.PrimitiveCollection<List<Guid>>("_actorIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("actor_ids");

                    b.HasKey("Id");

                    b.HasIndex("_actorIds")
                        .HasDatabaseName("ix_world_events_actor_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_actorIds"), "gin");

                    b.HasIndex("WorldId", "CorrelationId", "CausalityDepth")
                        .HasDatabaseName("ix_world_events_correlation");

                    b.HasIndex("WorldId", "PositionX", "PositionY")
                        .HasDatabaseName("ix_world_events_world_position");

                    b.HasIndex("WorldId", "TimestampUtc", "Id")
                        .HasDatabaseName("ix_world_events_world_timeline");

                    b.HasIndex("WorldId", "Type", "TimestampUtc")
                        .HasDatabaseName("ix_world_events_world_type_time");

                    b.ToTable("world_events", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_world_events_causality_depth", "causality_depth >= 0");

                            t.HasCheckConstraint("ck_world_events_cause_depth", "(causality_depth = 0 AND causation_id IS NULL) OR (causality_depth > 0 AND causation_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_world_events_correlation", "correlation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_world_events_payload_version", "payload_version > 0");

                            t.HasCheckConstraint("ck_world_events_position", "(position_x IS NULL AND position_y IS NULL) OR (position_x IS NOT NULL AND position_y IS NOT NULL AND position_x >= 0 AND position_y >= 0)");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Factions.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DissolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dissolved_at_utc");

                    b.Property<Guid?>("LeaderActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("leader_actor_id");

                    b.Property<decimal>("MilitaryPower")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("military_power");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<decimal>("Wealth")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("wealth");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<string>("_controlledCityIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("controlled_city_ids");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history");

                    b.Property<string>("_memberActorIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("member_actor_ids");

                    b.Property<string>("_relations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("relations");

                    b.HasKey("Id");

                    b.HasIndex("LeaderActorId")
                        .HasDatabaseName("ix_factions_leader");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_factions_world_name");

                    b.HasIndex("WorldId", "Status")
                        .HasDatabaseName("ix_factions_world_status");

                    b.ToTable("factions", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_factions_dissolved_state", "(status = 'Dissolved' AND dissolved_at_utc IS NOT NULL AND leader_actor_id IS NULL) OR (status = 'Active' AND dissolved_at_utc IS NULL AND leader_actor_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_factions_military_power", "military_power >= 0");

                            t.HasCheckConstraint("ck_factions_version", "version >= 0");

                            t.HasCheckConstraint("ck_factions_wealth", "wealth >= 0");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Factions.FactionTerritoryTile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("FactionId")
                        .HasDatabaseName("ix_faction_territory_faction");

                    b.HasIndex("WorldId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("ux_faction_territory_world_active_position")
                        .HasFilter("is_active");

                    b.ToTable("faction_territory_tiles", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_faction_territory_tiles_active", "(is_active AND released_at_utc IS NULL) OR (NOT is_active AND released_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_faction_territory_tiles_x", "x >= 0");

                            t.HasCheckConstraint("ck_faction_territory_tiles_y", "y >= 0");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Resources.ResourceDeposit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Capacity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at_utc");

                    b.Property<Guid?>("DiscoveredByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovered_by_actor_id");

                    b.Property<string>("InventoryItemCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("inventory_item_code");

                    b.Property<bool>("IsDiscovered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discovered");

                    b.Property<Guid?>("LastConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_consumer_id");

                    b.Property<string>("LastConsumerKind")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("last_consumer_kind");

                    b.Property<DateTimeOffset>("LastRegeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_regenerated_at_utc");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RegenerationPerWorldHour")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("regeneration_per_world_hour");

                    b.Property<int>("RegionX")
                        .HasColumnType("integer")
                        .HasColumnName("region_x");

                    b.Property<int>("RegionY")
                        .HasColumnType("integer")
                        .HasColumnName("region_y");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("resource_code");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SourceWorldEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_world_event_id");

                    b.Property<Guid?>("TileId")
                        .HasColumnType("uuid")
                        .HasColumnName("tile_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("TileId")
                        .IsUnique()
                        .HasDatabaseName("ux_resource_deposits_tile")
                        .HasFilter("tile_id IS NOT NULL");

                    b.HasIndex("WorldId", "IsDiscovered", "ResourceCode")
                        .HasDatabaseName("ix_resource_deposits_world_discovered_resource");

                    b.HasIndex("WorldId", "RegionX", "RegionY", "ResourceCode")
                        .HasDatabaseName("ix_resource_deposits_world_region_resource");

                    b.ToTable("resource_deposits", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_resource_deposits_discovery", "(is_discovered AND discovered_by_actor_id IS NOT NULL AND discovered_at_utc IS NOT NULL) OR (NOT is_discovered AND discovered_by_actor_id IS NULL AND discovered_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_resource_deposits_location", "(scope = 'Tile' AND tile_id IS NOT NULL) OR (scope = 'Region' AND tile_id IS NULL)");

                            t.HasCheckConstraint("ck_resource_deposits_quantity", "quantity >= 0 AND capacity > 0 AND quantity <= capacity");

                            t.HasCheckConstraint("ck_resource_deposits_regeneration", "regeneration_per_world_hour >= 0");

                            t.HasCheckConstraint("ck_resource_deposits_version", "version >= 0");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Tile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BiomeClassificationConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("biome_classification_confidence");

                    b.Property<string>("BiomeClassificationOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("biome_classification_origin");

                    b.Property<string>("BiomeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("biome_code");

                    b.Property<short>("Elevation")
                        .HasColumnType("smallint")
                        .HasColumnName("elevation");

                    b.Property<decimal>("Humidity")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("humidity");

                    b.Property<Guid?>("ResourceDepositId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_deposit_id");

                    b.Property<Guid?>("StructureId")
                        .HasColumnType("uuid")
                        .HasColumnName("structure_id");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("temperature_celsius");

                    b.Property<string>("TerrainCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("terrain_code");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.PrimitiveCollection<Guid[]>("_occupantIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("occupant_ids");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("ux_tiles_world_position");

                    b.ToTable("tiles", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.World", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_size");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsSimulationRunning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_simulation_running");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("worlds", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.WorldClock", b =>
                {
                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<DateTimeOffset>("CurrentInstant")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_instant");

                    b.Property<DateTimeOffset>("LastSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at_utc");

                    b.Property<decimal>("RealTimeMultiplier")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("real_time_multiplier");

                    b.Property<TimeSpan>("TickDuration")
                        .HasColumnType("interval")
                        .HasColumnName("tick_duration");

                    b.HasKey("WorldId");

                    b.ToTable("world_clocks", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.MapEditOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AffectedTiles")
                        .HasColumnType("integer")
                        .HasColumnName("affected_tiles");

                    b.Property<string>("Brush")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("brush");

                    b.Property<JsonDocument>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "CreatedAtUtc")
                        .HasDatabaseName("ix_map_edits_world_created");

                    b.ToTable("map_edit_operations", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.PersistenceCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_persistence_checkpoints_created_at_utc");

                    b.ToTable("persistence_checkpoints", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.WorldMapSourceImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("GridResolution")
                        .HasColumnType("integer")
                        .HasColumnName("grid_resolution");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("media_type");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_height");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_width");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_world_source_image_sha256");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_world_source_image_world");

                    b.ToTable("world_map_source_images", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.CreatureActor", b =>
                {
                    b.HasBaseType("RpgWorld.Domain.Actors.Actor");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_actors_npc_energy", "actor_type <> 'npc' OR (energy IS NOT NULL AND energy BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_hunger", "actor_type <> 'npc' OR (hunger IS NOT NULL AND hunger BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_money", "actor_type <> 'npc' OR (money IS NOT NULL AND money >= 0)");

                            t.HasCheckConstraint("ck_actors_npc_state_required", "actor_type <> 'npc' OR (needs_updated_at IS NOT NULL AND family_ids IS NOT NULL AND goals IS NOT NULL)");

                            t.HasCheckConstraint("ck_actors_npc_traits_required", "actor_type <> 'npc' OR trait_codes IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("creature");
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.NpcActor", b =>
                {
                    b.HasBaseType("RpgWorld.Domain.Actors.Actor");

                    b.Property<decimal>("Energy")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("energy");

                    b.Property<Guid?>("HomeStructureId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_structure_id");

                    b.Property<int?>("HomeX")
                        .HasColumnType("integer")
                        .HasColumnName("home_x");

                    b.Property<int?>("HomeY")
                        .HasColumnType("integer")
                        .HasColumnName("home_y");

                    b.Property<decimal>("Hunger")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hunger");

                    b.Property<string>("Job")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("job");

                    b.Property<decimal>("Money")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("money");

                    b.Property<DateTimeOffset>("NeedsUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("needs_updated_at");

                    b.Property<Guid?>("ResidentCityId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_city_id");

                    b.Property<string>("_familyIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("family_ids");

                    b.Property<string>("_goals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("goals");

                    b.Property<string>("_traitCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trait_codes");

                    b.HasIndex("ResidentCityId");

                    b.HasIndex("WorldId", "Energy")
                        .HasDatabaseName("ix_actors_npc_energy")
                        .HasFilter("actor_type = 'npc' AND status <> 'Dead'");

                    b.HasIndex("WorldId", "Hunger")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_actors_npc_hunger")
                        .HasFilter("actor_type = 'npc' AND status <> 'Dead'");

                    b.HasIndex("WorldId", "Job")
                        .HasDatabaseName("ix_actors_npc_job")
                        .HasFilter("actor_type = 'npc'");

                    b.HasIndex("WorldId", "ResidentCityId")
                        .HasDatabaseName("ix_actors_npc_resident_city")
                        .HasFilter("actor_type = 'npc' AND resident_city_id IS NOT NULL");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_actors_npc_energy", "actor_type <> 'npc' OR (energy IS NOT NULL AND energy BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_hunger", "actor_type <> 'npc' OR (hunger IS NOT NULL AND hunger BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_money", "actor_type <> 'npc' OR (money IS NOT NULL AND money >= 0)");

                            t.HasCheckConstraint("ck_actors_npc_state_required", "actor_type <> 'npc' OR (needs_updated_at IS NOT NULL AND family_ids IS NOT NULL AND goals IS NOT NULL)");

                            t.HasCheckConstraint("ck_actors_npc_traits_required", "actor_type <> 'npc' OR trait_codes IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("npc");
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.PlayerActor", b =>
                {
                    b.HasBaseType("RpgWorld.Domain.Actors.Actor");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_actors_npc_energy", "actor_type <> 'npc' OR (energy IS NOT NULL AND energy BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_hunger", "actor_type <> 'npc' OR (hunger IS NOT NULL AND hunger BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_money", "actor_type <> 'npc' OR (money IS NOT NULL AND money >= 0)");

                            t.HasCheckConstraint("ck_actors_npc_state_required", "actor_type <> 'npc' OR (needs_updated_at IS NOT NULL AND family_ids IS NOT NULL AND goals IS NOT NULL)");

                            t.HasCheckConstraint("ck_actors_npc_traits_required", "actor_type <> 'npc' OR trait_codes IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("player");
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Actor", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Housing.HousingConstruction", b =>
                {
                    b.HasOne("RpgWorld.Domain.Actors.NpcActor", null)
                        .WithMany()
                        .HasForeignKey("OwnerActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Memories.NpcMemory", b =>
                {
                    b.HasOne("RpgWorld.Domain.Actors.NpcActor", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.PlayerTileKnowledge", b =>
                {
                    b.HasOne("RpgWorld.Domain.Actors.PlayerActor", null)
                        .WithMany()
                        .HasForeignKey("PlayerActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Chunk", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Cities.City", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Cities.CityTerritoryTile", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.Cities.City", null)
                        .WithMany("_territoryTiles")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Events.WorldConsequence", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Events.WorldEvent", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Factions.Faction", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Factions.FactionTerritoryTile", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.Factions.Faction", null)
                        .WithMany("_territoryTiles")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Resources.ResourceDeposit", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.Tile", null)
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Tile", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.WorldClock", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithOne()
                        .HasForeignKey("RpgWorld.Domain.Worlds.WorldClock", "WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.MapEditOperation", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.WorldMapSourceImage", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithOne()
                        .HasForeignKey("RpgWorld.Infrastructure.Persistence.WorldMapSourceImage", "WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.NpcActor", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.Cities.City", null)
                        .WithMany()
                        .HasForeignKey("ResidentCityId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Cities.City", b =>
                {
                    b.Navigation("_territoryTiles");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Factions.Faction", b =>
                {
                    b.Navigation("_territoryTiles");
                });
#pragma warning restore 612, 618
        }
    }
}
