// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RpgWorld.Infrastructure.Persistence;

#nullable disable

namespace RpgWorld.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RpgWorldDbContext))]
    [Migration("20260831090516_AutonomousNpcHousing")]
    partial class AutonomousNpcHousing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rpg_world")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RpgWorld.Domain.Actors.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentAction")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("current_action");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<int>("MaximumHealth")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_health");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.Property<string>("_attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("_inventory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory");

                    b.Property<string>("_relationships")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("relationships");

                    b.Property<string>("_reputation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reputation");

                    b.Property<string>("actor_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Status")
                        .HasDatabaseName("ix_actors_world_status");

                    b.HasIndex("WorldId", "X", "Y")
                        .HasDatabaseName("ix_actors_world_position");

                    b.ToTable("actors", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_actors_npc_energy", "actor_type <> 'npc' OR (energy IS NOT NULL AND energy BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_hunger", "actor_type <> 'npc' OR (hunger IS NOT NULL AND hunger BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_money", "actor_type <> 'npc' OR (money IS NOT NULL AND money >= 0)");

                            t.HasCheckConstraint("ck_actors_npc_state_required", "actor_type <> 'npc' OR (needs_updated_at IS NOT NULL AND family_ids IS NOT NULL AND goals IS NOT NULL)");

                            t.HasCheckConstraint("ck_actors_npc_traits_required", "actor_type <> 'npc' OR trait_codes IS NOT NULL");
                        });

                    b.HasDiscriminator<string>("actor_type").HasValue("Actor");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Housing.HousingConstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("ConsumedStone")
                        .HasColumnType("integer")
                        .HasColumnName("consumed_stone");

                    b.Property<int>("ConsumedWood")
                        .HasColumnType("integer")
                        .HasColumnName("consumed_wood");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_actor_id");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<int>("RequiredStone")
                        .HasColumnType("integer")
                        .HasColumnName("required_stone");

                    b.Property<int>("RequiredWood")
                        .HasColumnType("integer")
                        .HasColumnName("required_wood");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.Property<string>("_residentActorIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resident_actor_ids");

                    b.HasKey("Id");

                    b.HasIndex("OwnerActorId")
                        .IsUnique()
                        .HasDatabaseName("ux_housing_constructions_active_owner")
                        .HasFilter("status = 'InProgress'");

                    b.HasIndex("WorldId", "Status")
                        .HasDatabaseName("ix_housing_constructions_world_status");

                    b.HasIndex("WorldId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("ux_housing_constructions_world_position");

                    b.ToTable("housing_constructions", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_housing_constructions_progress", "progress BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Memories.NpcMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<string>("_payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_npc_memories_expiration")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("ActorId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_npc_memories_actor_created");

                    b.HasIndex("ActorId", "TargetId", "Importance")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_npc_memories_actor_target_importance");

                    b.ToTable("npc_memories", "rpg_world", t =>
                        {
                            t.HasCheckConstraint("ck_npc_memories_importance", "importance BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AggregateEconomicOutput")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("aggregate_economic_output");

                    b.Property<decimal>("AggregateMilitaryStrength")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("aggregate_military_strength");

                    b.Property<int>("AggregatePopulation")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_population");

                    b.Property<decimal>("AggregateProductionOutput")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("aggregate_production_output");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("integer")
                        .HasColumnName("coordinate_x");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("integer")
                        .HasColumnName("coordinate_y");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("OriginX")
                        .HasColumnType("integer")
                        .HasColumnName("origin_x");

                    b.Property<int>("OriginY")
                        .HasColumnType("integer")
                        .HasColumnName("origin_y");

                    b.Property<string>("SimulationLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Abstract")
                        .HasColumnName("simulation_level");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "CoordinateX", "CoordinateY")
                        .IsUnique()
                        .HasDatabaseName("ux_chunks_world_coordinate");

                    b.ToTable("chunks", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Tile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BiomeClassificationConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("biome_classification_confidence");

                    b.Property<string>("BiomeClassificationOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("biome_classification_origin");

                    b.Property<string>("BiomeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("biome_code");

                    b.Property<short>("Elevation")
                        .HasColumnType("smallint")
                        .HasColumnName("elevation");

                    b.Property<decimal>("Humidity")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("humidity");

                    b.Property<Guid?>("ResourceDepositId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_deposit_id");

                    b.Property<Guid?>("StructureId")
                        .HasColumnType("uuid")
                        .HasColumnName("structure_id");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("temperature_celsius");

                    b.Property<string>("TerrainCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("terrain_code");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.PrimitiveCollection<Guid[]>("_occupantIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("occupant_ids");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "X", "Y")
                        .IsUnique()
                        .HasDatabaseName("ux_tiles_world_position");

                    b.ToTable("tiles", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.World", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_size");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsSimulationRunning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_simulation_running");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("worlds", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.WorldClock", b =>
                {
                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<DateTimeOffset>("CurrentInstant")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_instant");

                    b.Property<DateTimeOffset>("LastSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at_utc");

                    b.Property<decimal>("RealTimeMultiplier")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("real_time_multiplier");

                    b.Property<TimeSpan>("TickDuration")
                        .HasColumnType("interval")
                        .HasColumnName("tick_duration");

                    b.HasKey("WorldId");

                    b.ToTable("world_clocks", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.MapEditOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AffectedTiles")
                        .HasColumnType("integer")
                        .HasColumnName("affected_tiles");

                    b.Property<string>("Brush")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("brush");

                    b.Property<JsonDocument>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "CreatedAtUtc")
                        .HasDatabaseName("ix_map_edits_world_created");

                    b.ToTable("map_edit_operations", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.PersistenceCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_persistence_checkpoints_created_at_utc");

                    b.ToTable("persistence_checkpoints", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.WorldMapSourceImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("GridResolution")
                        .HasColumnType("integer")
                        .HasColumnName("grid_resolution");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("media_type");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_height");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_width");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_world_source_image_sha256");

                    b.HasIndex("WorldId")
                        .IsUnique()
                        .HasDatabaseName("ux_world_source_image_world");

                    b.ToTable("world_map_source_images", "rpg_world");
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.CreatureActor", b =>
                {
                    b.HasBaseType("RpgWorld.Domain.Actors.Actor");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_actors_npc_energy", "actor_type <> 'npc' OR (energy IS NOT NULL AND energy BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_hunger", "actor_type <> 'npc' OR (hunger IS NOT NULL AND hunger BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_money", "actor_type <> 'npc' OR (money IS NOT NULL AND money >= 0)");

                            t.HasCheckConstraint("ck_actors_npc_state_required", "actor_type <> 'npc' OR (needs_updated_at IS NOT NULL AND family_ids IS NOT NULL AND goals IS NOT NULL)");

                            t.HasCheckConstraint("ck_actors_npc_traits_required", "actor_type <> 'npc' OR trait_codes IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("creature");
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.NpcActor", b =>
                {
                    b.HasBaseType("RpgWorld.Domain.Actors.Actor");

                    b.Property<decimal>("Energy")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("energy");

                    b.Property<Guid?>("HomeStructureId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_structure_id");

                    b.Property<int?>("HomeX")
                        .HasColumnType("integer")
                        .HasColumnName("home_x");

                    b.Property<int?>("HomeY")
                        .HasColumnType("integer")
                        .HasColumnName("home_y");

                    b.Property<decimal>("Hunger")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hunger");

                    b.Property<string>("Job")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("job");

                    b.Property<decimal>("Money")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("money");

                    b.Property<DateTimeOffset>("NeedsUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("needs_updated_at");

                    b.Property<string>("_familyIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("family_ids");

                    b.Property<string>("_goals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("goals");

                    b.Property<string>("_traitCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trait_codes");

                    b.HasIndex("WorldId", "Energy")
                        .HasDatabaseName("ix_actors_npc_energy")
                        .HasFilter("actor_type = 'npc' AND status <> 'Dead'");

                    b.HasIndex("WorldId", "Hunger")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_actors_npc_hunger")
                        .HasFilter("actor_type = 'npc' AND status <> 'Dead'");

                    b.HasIndex("WorldId", "Job")
                        .HasDatabaseName("ix_actors_npc_job")
                        .HasFilter("actor_type = 'npc'");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_actors_npc_energy", "actor_type <> 'npc' OR (energy IS NOT NULL AND energy BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_hunger", "actor_type <> 'npc' OR (hunger IS NOT NULL AND hunger BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_money", "actor_type <> 'npc' OR (money IS NOT NULL AND money >= 0)");

                            t.HasCheckConstraint("ck_actors_npc_state_required", "actor_type <> 'npc' OR (needs_updated_at IS NOT NULL AND family_ids IS NOT NULL AND goals IS NOT NULL)");

                            t.HasCheckConstraint("ck_actors_npc_traits_required", "actor_type <> 'npc' OR trait_codes IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("npc");
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.PlayerActor", b =>
                {
                    b.HasBaseType("RpgWorld.Domain.Actors.Actor");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_actors_npc_energy", "actor_type <> 'npc' OR (energy IS NOT NULL AND energy BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_hunger", "actor_type <> 'npc' OR (hunger IS NOT NULL AND hunger BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_actors_npc_money", "actor_type <> 'npc' OR (money IS NOT NULL AND money >= 0)");

                            t.HasCheckConstraint("ck_actors_npc_state_required", "actor_type <> 'npc' OR (needs_updated_at IS NOT NULL AND family_ids IS NOT NULL AND goals IS NOT NULL)");

                            t.HasCheckConstraint("ck_actors_npc_traits_required", "actor_type <> 'npc' OR trait_codes IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue("player");
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Actor", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Housing.HousingConstruction", b =>
                {
                    b.HasOne("RpgWorld.Domain.Actors.NpcActor", null)
                        .WithMany()
                        .HasForeignKey("OwnerActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Actors.Memories.NpcMemory", b =>
                {
                    b.HasOne("RpgWorld.Domain.Actors.NpcActor", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Chunk", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.Tile", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Domain.Worlds.WorldClock", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithOne()
                        .HasForeignKey("RpgWorld.Domain.Worlds.WorldClock", "WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.MapEditOperation", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgWorld.Infrastructure.Persistence.WorldMapSourceImage", b =>
                {
                    b.HasOne("RpgWorld.Domain.Worlds.World", null)
                        .WithOne()
                        .HasForeignKey("RpgWorld.Infrastructure.Persistence.WorldMapSourceImage", "WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
